# Generated by Django 5.0.4 on 2025-02-19 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField()),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
                ('otp', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
